#feishu_app_zntz
feishu_app_id: cli_a81807b812b7901c
feishu_app_secret: wGTNLAxJiZBCoBvht4b7UbeBmSkWprYw

#feishu_mt_zntz
app_token: PGnFbf9dYaUggjsGs8NcW2Apn4b
table_id_zntz: tblqH6vPJgTwyTYH
table_id_lx: tblJCBmamebHMJJj
table_id_cyp: tbloAUrQkhEIIanN
table_id_zdh: tblxtyKeHorfu6SO
table_id_zs: tbl7rNQBQmnPwAvi

#